# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Untitled' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Untitled
  pod 'SnapKit', '~> 5.6.0'
  pod 'AnyFormatKit'
  target 'UntitledTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UntitledUITests' do
    # Pods for testing
  end

end
